#!/bin/sh

alias grep='grep --color=auto'

alias ls='exa --icons --group-directories-first'
alias la='ls -lah'

alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gl='git log --all --decorate --oneline --graph'

alias vim='nvim'
alias vi='nvim'

alias vconf='vim +"cd $conf/nvim"'
alias zconf='vim +"cd $conf/zsh"'

alias luamake=/home/archwsl/src/lua-language-server/3rd/luamake/luamake
