#!/bin/sh

alias grep='grep --color=auto'

alias ls='exa --icons --group-directories-first'
alias la='ls -lah'

alias gs='git status'
alias ga='git add'
alias gaa='git add -A'
alias gc='git commit'
alias gcm='git commit -m'
alias gl='git log --all --decorate --oneline --graph'

alias vim='nvim'
alias vi='nvim'

alias vconf='nvim $conf/nvim/init.lua -c "cd %:p:h"'
alias zconf='nvim $conf/zsh/zshrc -c "cd %:p:h"'
