#!/bin/sh

alias grep="grep --color=auto"

alias ls="exa --icons --group-directories-first"
alias la="ls -lah"

alias gs="git status"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gcm="git commit -m"

alias vim="nvim"
alias vi="nvim"

alias stow="stow -d $DOTS -t $HOME"

alias vconf="nvim $DOTS/wsl/etc/nvim/init.vim -c 'cd %:p:h'"
alias zconf="nvim $DOTS/wsl/etc/zsh/zshrc -c 'cd %:p:h'"
