#!/usr/bin/env zsh

# stolen from willeccles/cpm, switched doas and sudo
SUDO=
if command -v doas >/dev/null && [ -f /etc/doas.conf ]; then
    SUDO=doas
elif command -v sudo >/dev/null; then
    SUDO=sudo
elif [ "$(whoami)" != root ]; then
    SUDO='su root -c '\''"$@"'\'' -- -'
fi

if ! subsystemctl is-running; then
  echo -n "Start systemd bottle? [y/N]: "
  read -t 3 -qr yn
  echo

  if [[ $yn = "y" ]]; then
    echo "Entering bottle:"
    $SUDO subsystemctl start
  fi
fi
