#!/usr/bin/env zsh

source ~/usr/git/znap/zsh-snap/znap.zsh

zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu select
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' matcher-list \
  'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
fpath=($ZDOTDIR/completions $fpath)

zstyle ':znap:*' plugins-dir ~/usr/git/znap

# History
set -k                  # comments
setopt histignorespace
setopt extended_history
setopt hist_ignore_dups
setopt share_history
setopt auto_cd          # cd by directory name
unsetopt flowcontrol    # disable <C-S> + <C-Q>

# Autocompletion
setopt NO_NOMATCH       # disable some globbing
setopt complete_in_word

# Plugins
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-completions
znap source zsh-users/zsh-history-substring-search
znap source zdharma/fast-syntax-highlighting

# Keybinds
bindkey '^[[H'  beginning-of-line              # Home
bindkey '^[[F'  end-of-line                    # End
bindkey '^[[2~' overwrite-mode                 # Insert
bindkey '^[[3~' delete-char                    # Delete
bindkey '^[[A'  up-line-or-history             # ArrowUp
bindkey '^[[B'  down-line-or-history           # ArrowDown
bindkey '^[[D'  backward-char                  # ArrowLeft
bindkey '^[[C'  forward-char                   # ArrowRight
bindkey '^[[5~' beginning-of-buffer-or-history # PageUp
bindkey '^[[6~' end-of-buffer-or-history       # PageDown
bindkey '^[[Z'  reverse-menu-complete          # S-Tab

# Aliases
. $ZDOTDIR/aliases

# Source stuff
. /home/archwsl/.nix-profile/etc/profile.d/nix.sh

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# Prompt
. $ZDOTDIR/prompt.zsh
# eval "$(starship init zsh)"
